# Generated by Django 6.0.3 on 2026-03-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=200, verbose_name='Imię i Nazwisko')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='autorzy/', verbose_name='Zdjęcie autora')),
            ],
            options={
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa gatunku')),
            ],
            options={
                'verbose_name_plural': 'Gatunki',
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('opis', models.TextField(verbose_name='Opis fabuły')),
                ('data_wydania', models.DateField(verbose_name='Data wydania')),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='okladki/', verbose_name='Okładka')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='bibliotech.autor')),
                ('gatunek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazki', to='bibliotech.gatunek')),
            ],
            options={
                'verbose_name_plural': 'Książki',
            },
        ),
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Dostępny'), ('W', 'Wypożyczony'), ('R', 'Zarezerwowany')], default='D', max_length=1)),
                ('kod_kreskowy', models.CharField(max_length=50, unique=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzemplarze', to='bibliotech.ksiazka')),
            ],
            options={
                'verbose_name_plural': 'Egzemplarze',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('data_waznosci', models.DateTimeField()),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotech.egzemplarz')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
    ]
