# Generated by Django 6.0.3 on 2026-03-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarz',
            name='aktualny_czytelnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wypozyczone_egzemplarze', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='termin_zwrotu',
            field=models.DateField(blank=True, null=True, verbose_name='Termin oddania'),
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_wyslano', models.BooleanField(default=False)),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotech.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Powiadomienia',
            },
        ),
    ]
