# Generated by Django 6.0.3 on 2026-03-18 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0002_egzemplarz_aktualny_czytelnik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAkcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akcja', models.CharField(choices=[('R', 'Rezerwacja'), ('W', 'Wypożyczenie'), ('Z', 'Zwrot'), ('A', 'Anulowanie rezerwacji')], max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='bibliotech.egzemplarz')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Czytelnik')),
            ],
            options={
                'verbose_name_plural': 'Historia Akcji',
                'ordering': ['-data'],
            },
        ),
    ]
