# Generated by Django 6.0.3 on 2026-03-18 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0003_logakcji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='data_wydania',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='rok_wydania',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)], verbose_name='Rok wydania'),
        ),
    ]
