# Generated by Django 6.0.3 on 2026-04-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0004_remove_ksiazka_data_wydania_ksiazka_rok_wydania'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='powiadomienie',
            old_name='czy_wyslano',
            new_name='czy_przeczytane',
        ),
        migrations.RenameField(
            model_name='powiadomienie',
            old_name='data_zapisu',
            new_name='data_stworzenia',
        ),
        migrations.AddField(
            model_name='powiadomienie',
            name='tresc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='powiadomienie',
            name='tytul',
            field=models.CharField(default='Powiadomienie', max_length=200),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='ksiazka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotech.ksiazka'),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiadomienia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ZapisNaPowiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotech.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uzytkownik', 'ksiazka')},
            },
        ),
    ]
